import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { ThemeContextProvider, ThemeType } from 'contexts/theme/theme-context';
import { Button } from 'components/button';
import axios from 'axios';


export const getServerSideProps: GetServerSideProps = async (context) => {

  const theme = (context.req.cookies?.theme ?? 'light') as ThemeType;
  let countries: any = await axios.get('https://restcountries.com/v3.1/all');

  return {
    props: { theme, countries: countries.data },
  }
}


const Home: NextPage<{theme: ThemeType, countries: any }> = ({ theme, countries }) => {
  
  console.log(countries[0].cca3);  

  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeContextProvider theme={ theme }>
        <div className="teste">
          <Button />
          {
            countries.map((country : any) => (
              <article key={country.name.common}>
                <h2>{ country.name.common }</h2>
              </article>
            ))
          }

        </div>
      </ThemeContextProvider>
    </>
  )
}

export default Home
